version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout

      - run:
          name: Install Cypress dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              xvfb \
              libnss3 \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libgtk-3-0 \
              libxss1 \
              libasound2 \
              libgbm1

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Cypress
          command: xvfb-run -- npx cypress run

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
